backend:
  name: github
  repo: ideas24h/gridsome-rr

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Cover Image", name: "coverImage", widget: "image", required: false}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Pros", name: "pros", widget: "markdown"}
      - {label: "Contras", name: "contras", widget: "markdown"}

